---
main:
  loop_sleep: 3600
  discord_username: Dittos
  discord_message: "**<:ditto:779008286192173076> disguises change!**\n**Before** `{}`\n**After** `{}`"
  discord_webhook: https://discord.com/api/webhooks/xxx/xxx-xxx
  sentry_dns:
  user_agent: "notiditto/0.2"
  log_level: INFO
